# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 21:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    operations = [
        migrations.CreateModel(
            name='UserSender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('group', models.CharField(max_length=255, verbose_name='Group')),
                ('send_to', models.CharField(max_length=255, verbose_name='Send_to')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
            ],
            options={
                'verbose_name': 'UserSender',
                'verbose_name_plural': 'UserSenders',
            },
        ),
    ]
